<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="FacebookPageTest"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="31.087">
  <properties />
            <testcase name="getLoginError" time="22.271" classname="com.pom.testcases.TestFacebookLoginPage">
                <failure type="java.lang.AssertionError"
                  message="The following asserts failed:
	expected [ The password that you&apos;ve entered is incorrect. Forgotten password?] but found [The password that you&apos;ve entered is incorrect. Forgotten password?]"
              >
<![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [ The password that you've entered is incorrect. Forgotten password?] but found [The password that you've entered is incorrect. Forgotten password?]
  org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
  com.pom.testcases.TestFacebookLoginPage.getLoginError(TestFacebookLoginPage.java:88)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="enterCredentials" time="8.816" classname="com.pom.testcases.TestFacebookLoginPage" />
      
</testsuite>
